# Generated by Django 5.2.15 on 2026-07-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('pink', 'Pink'), ('orange', 'Orange'), ('purple', 'Purple')], default='green', max_length=20),
        ),
    ]
